#' ---
#' title: "Kidney Cancer Main Analysis"
#' author: "Guerra, Bokov, Wilson"
#' date: "07/10/2017"
#' ---
#' 
#' ## Load libraries
require(magrittr); require("dtplyr"); require(dplyr);
require("ggplot2");require('readr');
#' ## Load local config file
source('./config.R');
#' ## Load data
#' 
#' This contains d0, which are counts by age, sex, and reference group
#load(inci_inputdata);
#' The inputdata is generated by the following bash command run on a collection 
#' of output files from chinotype:
#' `grep -H "^\"DEM|AGE\"" *.csv |awk -F, '{print $1 "," $2 "," $4 "," $5 "," $6 "," $7}'|sed -e "s/.csv:\"DEM|AGE\",\"DEM|AGE:/,/"|sed -e "s/\"//g" > kc_lc_agecounts.csv
`
#' 
d0 <- read.csv(inci_inputdata,header = F) %>% setNames(c('group','age','atrisk','frac_atrisk','cancer','frac_cancer'));
d0$agebin <- cut(d0$age,c(0,10*(2:7),Inf),include.lowest = T);
grepl()
#' ## First stage of tabulation
#' 
d0 %>% group_by(group,agebin) %>% 
  summarise(N=sum(atrisk),n=sum(cancer),pct=n/N) -> d1;

d1$sex <- d1$condition <- d1$group;
levels(d1$sex) <- levels(d1$group) %>% gsub('.*_f_.*','Female',.) %>% 
  gsub('.*_m_.*','Male',.) %>% ifelse(. %in% c('Male','Female'),.,' ');
levels(d1$cancer) <- levels(d1$cancer) %>% 
  ifelse(test=grepl('_kc$',.),yes='Kidney',no='Liver');
#' ## Age tables
#' 
cbind(
  subset(data.frame(d1),grepl('^nhw',group))
  ,subset(data.frame(d1),grepl('^hsp',group)));
#' ...and then I got lazy and copy-pasted to spreadsheet.
#' 
